



github:
#	pandoc intervent_parameter.md -o ../scripts/intervent_parameter.ipynb
#	pandoc biosafe.md -o ../scripts/biosafe.ipynb#
#	pandoc cost_evaluation.md -o ../scripts/cost_evaluation.ipynb
#	pandoc landowner_evaluation.md -o ../scripts/landowner_evaluation.ipynb
	pandoc measure_evaluation.md -o ../scripts/measure_evaluation.ipynb


devel:
#	pandoc intervent_parameter.md -o ../scripts/intervent_parameter_dev.ipynb
#	pandoc biosafe.md -o ../scripts/biosafe_dev.ipynb
#	pandoc cost_evaluation.md -o ../scripts/cost_evaluation_dev.ipynb
#	pandoc landowner_evaluation.md -o ../scripts/landowner_evaluation_dev.ipynb
	pandoc measure_evaluation.md -o ../scripts/measure_evaluation_dev.ipynb
