



github:
	pandoc intervent_parameter.md -o ../scripts/intervent_parameter.ipynb
#	pandoc biosafe.md -o ../scripts/biosafe.ipynb
	pandoc cost_evaluation.md -o ../scripts/cost_evaluation.ipynb


devel:
#	pandoc intervent_parameter.md -o ../scripts/intervent_parameter_dev.ipynb
#	pandoc biosafe.md -o ../scripts/biosafe_dev.ipynb
	pandoc cost_evaluation.md -o ../scripts/cost_evaluation_dev.ipynb
