



github:
	pandoc intervention_planning.md -o ../scripts/intervention_planning.ipynb
	pandoc biodiversity_evaluation.md -o ../scripts/biodiversity_evaluation.ipynb
	pandoc cost_evaluation.md -o ../scripts/cost_evaluation.ipynb
	pandoc landowner_evaluation.md -o ../scripts/landowner_evaluation.ipynb
	pandoc measure_evaluation.md -o ../scripts/measure_evaluation.ipynb


devel:
	pandoc intervention_planning.md -o ../scripts/intervention_planning_dev.ipynb
	pandoc biodiversity_evaluation.md -o ../scripts/biodiversity_evaluation_dev.ipynb
	pandoc cost_evaluation.md -o ../scripts/cost_evaluation_dev.ipynb
	pandoc landowner_evaluation.md -o ../scripts/landowner_evaluation_dev.ipynb
	pandoc measure_evaluation.md -o ../scripts/measure_evaluation_dev.ipynb
